version: '3.4'

services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dockerkompose-platform-container
    image: dockerkompose-platform-image:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9090:80
      - 4343:443
  database:
    build:
      context: .
      dockerfile: ./apps/postgres/Dockerfile
    container_name: dockerkompose-database-container
    image: dockerkompose-database-image
    restart: always
    ports:
      - 5437:5432

    